### PR TITLE
fetch upstream

### PR DESCRIPTION
**Pull request by shadichy**

### CODE REVIEW

**Comment by kimariterikishi** [comment]
ear developer!

Something is wrong with the package you have created. I have recommended it to two people, one of them reported that the PKGBUILD file is incomplete, the application does not install. Another tested it like this (I can show the output in Hungarian):

```
sudo pacman-key --recv-key 50B2C005A67B264F --keyserver 'hkp://keyserver.ubuntu.com:80'
[sudo] *** jelszava:  
gpg: key 50B2C005A67B264F: public key "Bluewhale Robot <[randoms@bwbot.org](mailto:randoms@bwbot.org)>" imported
gpg:      Összesen feldolgoztam: 1
gpg:                 importálva: 1
```

```
yay -S systemback
-> Could not find all required packages:
       systemback (Target)
```

```
git clone https://github.com/shadichy/systemback-archlinux
Cloning into 'systemback-archlinux'...
remote: Enumerating objects: 272, done.
remote: Counting objects: 100% (272/272), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 272 (delta 140), reused 213 (delta 83), pack-reused 0
Receiving objects: 100% (272/272), 1.89 MiB | 10.26 MiB/s, done.
Resolving deltas: 100% (140/140), done.
```

`cd systemback-archlinux`

```
makepkg -si
/home/***/systemback-archlinux/PKGBUILD: sor: 16: szintaktikai hiba „{}” váratlan token közelében
/home/***/systemback-archlinux/PKGBUILD: sor: 16: `build() {}'
==> HIBA: Nem sikerült /home/andrea/systemback-archlinux/PKGBUILD beolvasása
```

Please check what the problem might be and fix it as you can, because at least many people would like to use the well working Systemback application on Arch Linux.

Sorry there is no "issue", but that's why I'm writing here.

Best Regards
kimarite

**Comment by shadichy** [comment]
Dear @kimariterikishi 
Sorry, but I haven't done anything yet (haven't had time yet)
As you can see, PKGBUILD is empty
I'm apologize for this impatience

**Comment by kimariterikishi** [comment]
Dear @shadichy

The good news is that the Kende script (console application) works on Arch Linux.
Here is (not a graphical application):
https://gitlab.com/Kendek/systemback

You need the GNU Autoconf for the PKGBUILD file, i.e., a source that contains it.

I looked on Debian, this is how to download the source:

`sudo nano /etc/apt/sources.list.d/systemback.list`

The second line is the source, the new line:

```
deb [arch=amd64] http://mirrors.bwbot.org/ stable main
deb-src [arch=amd64] http://mirrors.bwbot.org/ stable main
```

Ctrl + O and Enter,
then Ctrl + X

Terminal:

`sudo apt-get update`

`apt-get source systemback`

`cd systemback-1.8.5/debian/source/`

Then the debuild application is recommended:
https://www.debian.org/doc/manuals/maint-guide/build.en.html#debuild

Manual:
https://man7.org/linux/man-pages/man1/dpkg-buildpackage.1.html

No, but I get a key error at end (LC_MESSAGES=C "lost" sorry):

```
N: 4 hints overridden (4 warnings); 1 unused override
Finished running lintian.
Now signing changes and any dsc files...
 signfile dsc systemback_1.8.5.dsc Zhang Weijia (randoms) <randoms@bwbot.org>
gpg: skipped "Zhang Weijia (randoms) <randoms@bwbot.org>": no secret key
gpg: /tmp/debsign.zj041ASL/systemback_1.8.5.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1112:
running debsign failed
```

Or you can use another solution, like the Arch Linux solution to get a .configure file from the Debian source (which is also available on the BluewhaleRobot GitHub site of course) :-)

Good luck! Looking forward to your solution.

Best regards,
kimarite

**Comment by shadichy** [comment]
Dear @kimariterikishi 
there is one big problem with `libsystemback`, that is the only thing I need to port to Arch Linux
Other components have no conflict 
Thanks

**Comment by shadichy** [comment]
Dear @kimariterikishi 
I'm glad to tell you that now you can successfully build this package (no doubt) 
But i'm not sure if it's usable or not :))

**Pull request merged**
